### PR TITLE
signup-validation

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
## Fixes  Issue #146 
Did the required changes as per the instructions for issue #146 . 
The validation message appears below the respective input if the validation conditions are not met.
Screenshot 2023-01-13 223815

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
**@DamyanBG**  can you please review my PR?

**Comment by DamyanBG** [comment]
> **@DamyanBG** can you please review my PR?

I already made a review and leaved a comment.

**Comment by AlfiyaSiddique** [comment]
> I already made a review and leaved a comment.

@DamyanBG  I am really not able to find the comment, where is it ?  Can you please guide me on this?

**Comment by DamyanBG** [comment]
I am not on the PC right now. I wrote comment related to Input component. You wrote required attribute for the input element, but we are reusing this component for non required fields too.

**Comment by AlfiyaSiddique** [comment]
> I am not on the PC right now. I wrote comment related to Input component. You wrote required attribute for the input element, but we are reusing this component for non required fields too.

Okay, I'll do the required changes.

**Comment by AlfiyaSiddique** [comment]
Removed the **required** attribute and maintain the functionality as it is

**Comment by DamyanBG** [comment]
Okay, I will merge your work and manual test later.

**Review by DamyanBG — APPROVED** [review]

**Pull request merged**
