### PR TITLE
Real estate app home validation form issue

### PR DESCRIPTION
**Pull request by oderinde300**
Added form validation to create-home form. Following these  rules:

title - required, min 3 chars max 150
city - required, min 3 chars max 150
address - required, min 3 chars max 150
longitude - max 50 chars
latitude - max 50 chars
price - required, valid integer, max 50 chars
year - required, valid integer, max 5 chars
description - required, min 5 chars, max 150

### CODE REVIEW

**Comment by DamyanBG** [comment]
Very good. Now I am waiting for the PR with the tests.

**Comment by oderinde300** [comment]
Thanks. I will work on it.

**Comment by oderinde300** [comment]
Hi, @DamyanBG  regarding the test. I can't write the test using vitest unless the react project was initialized with vite.

**Comment by DamyanBG** [comment]
Big minus for vitest then.

**Pull request closed without merging**
