### PR TITLE
Added validations to the home form

### PR DESCRIPTION
**Pull request by oderinde300**
Added form validations to the create-home and edit-home forms.

### CODE REVIEW

**Comment by DamyanBG** [comment]
Hi, your PR have conflicts.

**Comment by oderinde300** [comment]
Have resolved the conflicts

**Review by DamyanBG — APPROVED** [review]

**Comment by oderinde300** [comment]
Hi, Have resolved the conflicts.

**Comment by DamyanBG** [comment]
I merged the code without to take a look. You didn't resolved the conflict good. 

If you have time, please, fix the issue https://github.com/DamyanBG/real-estate-react-app/issues/178

**Pull request merged**
