### PR TITLE
created the /create-visitation page

### PR DESCRIPTION
**Pull request by oderinde300**

### CODE REVIEW

**Comment by oderinde300** [comment]
Created the create-visitation page. 

This is the code @DamyanBG

**Comment by DamyanBG** [comment]
`export const VISITATION_FIELDS = [
    {
        labelName: 'date',
        name: 'date',
        type: 'date'
    },
    {
        labelName: 'Start hour',
        name: 'start_hour',
        type: 'datetime-local'
    },
    {
        labelName: 'End hour',
        name: 'end_hour',
        type: 'datetime-local'
    },
    {
        labelName: 'Address',
        name: 'address',
    },
];`

**Comment by DamyanBG** [comment]
`<InputFormRow
                        key={vf.labelName}
                        type={vf.type}
                        labelName={vf.labelName}
                        name={vf.name}
                        value={validationInfo[vf.name]}
                        handleOnChange={handleOnChange}
                    />`

**Comment by DamyanBG** [comment]
you have to change the type of the inputs

**Comment by oderinde300** [comment]
okay. I will do that now

**Comment by oderinde300** [comment]
On page /create-visitation I implement a page where the users can create visitations. The required fields for that are:

Date
start hour
end hour
address
On submission I made a POST request to /visitation with JSON body, which contains the data from the fields + user id + jwt token + home_id or land_id from the URL.

**Comment by oderinde300** [comment]
Have made the necessary changes @DamyanBG. You can now merge the branch

**Review by DamyanBG — APPROVED** [review]

**Pull request merged**
